#
# coinList = [
# { 'market': 'KRW-BTC', 'korean_name': '비트코인', 'english_name': 'Bitcoin' },
# { 'market': 'KRW-ETH', 'korean_name': '이더리움', 'english_name': 'Ethereum' },
# { 'market': 'BTC-ETH', 'korean_name': '이더리움', 'english_name': 'Ethereum' },
# { 'market': 'BTC-LTC', 'korean_name': '라이트코인', 'english_name': 'Litecoin' },
# { 'market': 'BTC-XRP', 'korean_name': '리플', 'english_name': 'Ripple' },
# {
#   'market': 'BTC-ETC',
#   'korean_name': '이더리움클래식',
#   'english_name': 'Ethereum Classic'
# },
# { 'market': 'BTC-OMG', 'korean_name': '오미세고', 'english_name': 'OmiseGo' },
# { 'market': 'BTC-CVC', 'korean_name': '시빅', 'english_name': 'Civic' },
# { 'market': 'BTC-DGB', 'korean_name': '디지바이트', 'english_name': 'DigiByte' },
# {
#   'market': 'BTC-PAY',
#   'korean_name': '텐엑스페이토큰',
#   'english_name': 'TenX Pay Token'
# },
# { 'market': 'BTC-SC', 'korean_name': '시아코인', 'english_name': 'Siacoin' },
# {
#   'market': 'BTC-SNT',
#   'korean_name': '스테이터스네트워크토큰',
#   'english_name': 'Status Network Token'
# },
# { 'market': 'BTC-WAVES', 'korean_name': '웨이브', 'english_name': 'Waves' },
# { 'market': 'BTC-NMR', 'korean_name': '뉴메레르', 'english_name': 'Numeraire' },
# { 'market': 'BTC-XEM', 'korean_name': '넴', 'english_name': 'NEM' },
# {
#   'market': 'BTC-LBC',
#   'korean_name': '엘비알와이크레딧',
#   'english_name': 'LBRY Credits'
# },
# { 'market': 'BTC-QTUM', 'korean_name': '퀀텀', 'english_name': 'Qtum' },
# { 'market': 'BTC-NXT', 'korean_name': '엔엑스티', 'english_name': 'Nxt' },
# {
#   'market': 'BTC-BAT',
#   'korean_name': '베이직어텐션토큰',
#   'english_name': 'Basic Attention Token'
# },
# { 'market': 'BTC-LSK', 'korean_name': '리스크', 'english_name': 'Lisk' },
# { 'market': 'BTC-RDD', 'korean_name': '레드코인', 'english_name': 'ReddCoin' },
# { 'market': 'BTC-STEEM', 'korean_name': '스팀', 'english_name': 'Steem' },
# { 'market': 'BTC-DOGE', 'korean_name': '도지코인', 'english_name': 'Dogecoin' },
# { 'market': 'BTC-BNT', 'korean_name': '뱅코르', 'english_name': 'Bancor' },
# { 'market': 'BTC-XLM', 'korean_name': '스텔라루멘', 'english_name': 'Lumen' },
# { 'market': 'BTC-ARDR', 'korean_name': '아더', 'english_name': 'Ardor' },
# { 'market': 'BTC-KMD', 'korean_name': '코모도', 'english_name': 'Komodo' },
# { 'market': 'BTC-ARK', 'korean_name': '아크', 'english_name': 'Ark' },
# { 'market': 'BTC-ADX', 'korean_name': '애드엑스', 'english_name': 'AdEx' },
# { 'market': 'BTC-SYS', 'korean_name': '시스코인', 'english_name': 'SysCoin' },
# { 'market': 'BTC-ANT', 'korean_name': '아라곤', 'english_name': 'Aragon' },
# { 'market': 'BTC-STORJ', 'korean_name': '스토리지', 'english_name': 'Storj' },
# {
#   'market': 'BTC-GRS',
#   'korean_name': '그로스톨코인',
#   'english_name': 'Groestlcoin'
# },
# { 'market': 'BTC-REP', 'korean_name': '어거', 'english_name': 'Augur' },
# { 'market': 'BTC-RLC', 'korean_name': '아이젝', 'english_name': 'iEx.ec' },
# {
#   'market': 'BTC-EMC2',
#   'korean_name': '아인스타이늄',
#   'english_name': 'Einsteinium'
# },
# { 'market': 'USDT-BTC', 'korean_name': '비트코인', 'english_name': 'Bitcoin' },
# { 'market': 'USDT-ETH', 'korean_name': '이더리움', 'english_name': 'Ethereum' },
# { 'market': 'USDT-LTC', 'korean_name': '라이트코인', 'english_name': 'Litecoin' },
# { 'market': 'USDT-XRP', 'korean_name': '리플', 'english_name': 'Ripple' },
# {
#   'market': 'USDT-ETC',
#   'korean_name': '이더리움클래식',
#   'english_name': 'Ethereum Classic'
# },
# { 'market': 'KRW-NEO', 'korean_name': '네오', 'english_name': 'NEO' },
# { 'market': 'KRW-MTL', 'korean_name': '메탈', 'english_name': 'Metal' },
# { 'market': 'KRW-LTC', 'korean_name': '라이트코인', 'english_name': 'Litecoin' },
# { 'market': 'KRW-XRP', 'korean_name': '리플', 'english_name': 'Ripple' },
# {
#   'market': 'KRW-ETC',
#   'korean_name': '이더리움클래식',
#   'english_name': 'Ethereum Classic'
# },
# { 'market': 'KRW-OMG', 'korean_name': '오미세고', 'english_name': 'OmiseGo' },
# {
#   'market': 'KRW-SNT',
#   'korean_name': '스테이터스네트워크토큰',
#   'english_name': 'Status Network Token'
# },
# { 'market': 'KRW-WAVES', 'korean_name': '웨이브', 'english_name': 'Waves' },
# { 'market': 'KRW-XEM', 'korean_name': '넴', 'english_name': 'NEM' },
# { 'market': 'KRW-QTUM', 'korean_name': '퀀텀', 'english_name': 'Qtum' },
# { 'market': 'KRW-LSK', 'korean_name': '리스크', 'english_name': 'Lisk' },
# { 'market': 'KRW-STEEM', 'korean_name': '스팀', 'english_name': 'Steem' },
# { 'market': 'KRW-XLM', 'korean_name': '스텔라루멘', 'english_name': 'Lumen' },
# { 'market': 'KRW-ARDR', 'korean_name': '아더', 'english_name': 'Ardor' },
# { 'market': 'KRW-KMD', 'korean_name': '코모도', 'english_name': 'Komodo' },
# { 'market': 'KRW-ARK', 'korean_name': '아크', 'english_name': 'Ark' },
# { 'market': 'KRW-STORJ', 'korean_name': '스토리지', 'english_name': 'Storj' },
# {
#   'market': 'KRW-GRS',
#   'korean_name': '그로스톨코인',
#   'english_name': 'Groestlcoin'
# },
# { 'market': 'KRW-REP', 'korean_name': '어거', 'english_name': 'Augur' },
# {
#   'market': 'KRW-EMC2',
#   'korean_name': '아인스타이늄',
#   'english_name': 'Einsteinium'
# },
# { 'market': 'KRW-ADA', 'korean_name': '에이다', 'english_name': 'Ada' },
# { 'market': 'BTC-ADA', 'korean_name': '에이다', 'english_name': 'Ada' },
# {
#   'market': 'BTC-MANA',
#   'korean_name': '디센트럴랜드',
#   'english_name': 'Decentraland'
# },
# { 'market': 'USDT-OMG', 'korean_name': '오미세고', 'english_name': 'OmiseGo' },
# {
#   'market': 'KRW-SBD',
#   'korean_name': '스팀달러',
#   'english_name': 'SteemDollars'
# },
# {
#   'market': 'BTC-SBD',
#   'korean_name': '스팀달러',
#   'english_name': 'SteemDollars'
# },
# {
#   'market': 'BTC-RCN',
#   'korean_name': '리피오크레딧네트워크',
#   'english_name': 'Ripio Credit Network'
# },
# { 'market': 'BTC-VIB', 'korean_name': '바이버레이트', 'english_name': 'Viberate' },
# {
#   'market': 'KRW-POWR',
#   'korean_name': '파워렛저',
#   'english_name': 'Power ledger'
# },
# {
#   'market': 'BTC-POWR',
#   'korean_name': '파워렛저',
#   'english_name': 'Power ledger'
# },
# {
#   'market': 'KRW-BTG',
#   'korean_name': '비트코인골드',
#   'english_name': 'Bitcoin Gold'
# },
# { 'market': 'USDT-ADA', 'korean_name': '에이다', 'english_name': 'Ada' },
# {
#   'market': 'BTC-DNT',
#   'korean_name': '디스트릭트0x',
#   'english_name': 'district0x'
# },
# { 'market': 'BTC-IGNIS', 'korean_name': '이그니스', 'english_name': 'Ignis' },
# { 'market': 'BTC-SRN', 'korean_name': '시린토큰', 'english_name': 'Sirin Token' },
# { 'market': 'BTC-ZRX', 'korean_name': '제로엑스', 'english_name': '0x Protocol' },
# { 'market': 'BTC-TRX', 'korean_name': '트론', 'english_name': 'TRON' },
# { 'market': 'BTC-TUSD', 'korean_name': '트루USD', 'english_name': 'TrueUSD' },
# { 'market': 'BTC-LRC', 'korean_name': '루프링', 'english_name': 'Loopring' },
# { 'market': 'KRW-ICX', 'korean_name': '아이콘', 'english_name': 'Icon' },
# { 'market': 'KRW-EOS', 'korean_name': '이오스', 'english_name': 'EOS' },
# { 'market': 'BTC-DMT', 'korean_name': '디마켓', 'english_name': 'DMarket' },
# { 'market': 'USDT-TUSD', 'korean_name': '트루USD', 'english_name': 'TrueUSD' },
# { 'market': 'KRW-TRX', 'korean_name': '트론', 'english_name': 'TRON' },
# { 'market': 'BTC-POLY', 'korean_name': '폴리매쓰', 'english_name': 'Polymath' },
# { 'market': 'BTC-PRO', 'korean_name': '프로피', 'english_name': 'Propy' },
# { 'market': 'USDT-SC', 'korean_name': '시아코인', 'english_name': 'Siacoin' },
# { 'market': 'USDT-TRX', 'korean_name': '트론', 'english_name': 'TRON' },
# { 'market': 'KRW-SC', 'korean_name': '시아코인', 'english_name': 'Siacoin' },
# { 'market': 'KRW-IGNIS', 'korean_name': '이그니스', 'english_name': 'Ignis' },
# { 'market': 'KRW-ONT', 'korean_name': '온톨로지', 'english_name': 'Ontology' },
# { 'market': 'KRW-ZIL', 'korean_name': '질리카', 'english_name': 'Zilliqa' },
# { 'market': 'KRW-POLY', 'korean_name': '폴리매쓰', 'english_name': 'Polymath' },
# { 'market': 'KRW-ZRX', 'korean_name': '제로엑스', 'english_name': '0x Protocol' },
# { 'market': 'KRW-SRN', 'korean_name': '시린토큰', 'english_name': 'Sirin Token' },
# {
#   'market': 'KRW-LOOM',
#   'korean_name': '룸네트워크',
#   'english_name': 'Loom Network'
# },
# {
#   'market': 'BTC-BCH',
#   'korean_name': '비트코인캐시',
#   'english_name': 'Bitcoin Cash'
# },
# {
#   'market': 'USDT-BCH',
#   'korean_name': '비트코인캐시',
#   'english_name': 'Bitcoin Cash'
# },
# {
#   'market': 'KRW-BCH',
#   'korean_name': '비트코인캐시',
#   'english_name': 'Bitcoin Cash'
# },
# { 'market': 'BTC-MFT', 'korean_name': '메인프레임', 'english_name': 'Mainframe' },
# {
#   'market': 'BTC-LOOM',
#   'korean_name': '룸네트워크',
#   'english_name': 'Loom Network'
# },
# { 'market': 'KRW-ADX', 'korean_name': '애드엑스', 'english_name': 'AdEx' },
# {
#   'market': 'KRW-BAT',
#   'korean_name': '베이직어텐션토큰',
#   'english_name': 'Basic Attention Token'
# },
# { 'market': 'KRW-IOST', 'korean_name': '아이오에스티', 'english_name': 'IOST' },
# { 'market': 'BTC-RFR', 'korean_name': '리퍼리움', 'english_name': 'Refereum' },
# { 'market': 'KRW-DMT', 'korean_name': '디마켓', 'english_name': 'DMarket' },
# { 'market': 'KRW-RFR', 'korean_name': '리퍼리움', 'english_name': 'Refereum' },
# { 'market': 'USDT-DGB', 'korean_name': '디지바이트', 'english_name': 'DigiByte' },
# { 'market': 'KRW-CVC', 'korean_name': '시빅', 'english_name': 'Civic' },
# { 'market': 'KRW-IQ', 'korean_name': '에브리피디아', 'english_name': 'Everipedia' },
# { 'market': 'KRW-IOTA', 'korean_name': '아이오타', 'english_name': 'IOTA' },
# { 'market': 'BTC-RVN', 'korean_name': '레이븐코인', 'english_name': 'Ravencoin' },
# {
#   'market': 'BTC-BFT',
#   'korean_name': '비에프토큰',
#   'english_name': 'BnkToTheFuture'
# },
# { 'market': 'BTC-GO', 'korean_name': '고체인', 'english_name': 'GoChain' },
# {
#   'market': 'BTC-UPP',
#   'korean_name': '센티넬프로토콜',
#   'english_name': 'Sentinel Protocol'
# },
# { 'market': 'BTC-ENJ', 'korean_name': '엔진코인', 'english_name': 'Enjin' },
# { 'market': 'KRW-MFT', 'korean_name': '메인프레임', 'english_name': 'Mainframe' },
# { 'market': 'BTC-DTA', 'korean_name': '데이터', 'english_name': 'DATA' },
# { 'market': 'BTC-EDR', 'korean_name': '엔도르', 'english_name': 'Endor' },
# { 'market': 'KRW-ONG', 'korean_name': '온톨로지가스', 'english_name': 'ONG' },
# { 'market': 'KRW-GAS', 'korean_name': '가스', 'english_name': 'GAS' },
# { 'market': 'BTC-MTL', 'korean_name': '메탈', 'english_name': 'Metal' },
# {
#   'market': 'KRW-UPP',
#   'korean_name': '센티넬프로토콜',
#   'english_name': 'Sentinel Protocol'
# },
# { 'market': 'KRW-ELF', 'korean_name': '엘프', 'english_name': 'aelf' },
# { 'market': 'BTC-PMA', 'korean_name': '퓨마페이', 'english_name': 'PumaPay' },
# { 'market': 'USDT-DOGE', 'korean_name': '도지코인', 'english_name': 'Dogecoin' },
# {
#   'market': 'USDT-ZRX',
#   'korean_name': '제로엑스',
#   'english_name': '0x Protocol'
# },
# { 'market': 'USDT-RVN', 'korean_name': '레이븐코인', 'english_name': 'Ravencoin' },
# {
#   'market': 'USDT-BAT',
#   'korean_name': '베이직어텐션토큰',
#   'english_name': 'Basic Attention Token'
# },
# {
#   'market': 'KRW-KNC',
#   'korean_name': '카이버네트워크',
#   'english_name': 'Kyber Network'
# },
# {
#   'market': 'BTC-PAX',
#   'korean_name': '팩소스스탠다드',
#   'english_name': 'Paxos Standard'
# },
# { 'market': 'BTC-MOC', 'korean_name': '모스코인', 'english_name': 'Moss Coin' },
# { 'market': 'BTC-NPXS', 'korean_name': '펀디엑스', 'english_name': 'Pundi X' },
# { 'market': 'BTC-ZIL', 'korean_name': '질리카', 'english_name': 'Zilliqa' },
# {
#   'market': 'KRW-BSV',
#   'korean_name': '비트코인에스브이',
#   'english_name': 'Bitcoin SV'
# },
# {
#   'market': 'BTC-BSV',
#   'korean_name': '비트코인에스브이',
#   'english_name': 'Bitcoin SV'
# },
# { 'market': 'BTC-IOST', 'korean_name': '아이오에스티', 'english_name': 'IOST' },
# {
#   'market': 'KRW-THETA',
#   'korean_name': '쎄타토큰',
#   'english_name': 'Theta Token'
# },
# {
#   'market': 'BTC-NCASH',
#   'korean_name': '뉴클리어스비전',
#   'english_name': 'Nucleus Vision'
# },
# { 'market': 'KRW-EDR', 'korean_name': '엔도르', 'english_name': 'Endor' },
# { 'market': 'BTC-DENT', 'korean_name': '덴트', 'english_name': 'Dent' },
# { 'market': 'KRW-QKC', 'korean_name': '쿼크체인', 'english_name': 'QuarkChain' },
# { 'market': 'BTC-BTM', 'korean_name': '바이텀', 'english_name': 'Bytom' },
# { 'market': 'BTC-ELF', 'korean_name': '엘프', 'english_name': 'aelf' },
# { 'market': 'KRW-BTT', 'korean_name': '비트토렌트', 'english_name': 'BitTorrent' },
# { 'market': 'BTC-BTT', 'korean_name': '비트토렌트', 'english_name': 'BitTorrent' },
# { 'market': 'BTC-VITE', 'korean_name': '비트토큰', 'english_name': 'Vite' },
# { 'market': 'BTC-IOTX', 'korean_name': '아이오텍스', 'english_name': 'IoTeX' },
# {
#   'market': 'BTC-SOLVE',
#   'korean_name': '솔브케어',
#   'english_name': 'Solve.Care'
# },
# { 'market': 'BTC-NKN', 'korean_name': '엔케이엔', 'english_name': 'NKN' },
# { 'market': 'BTC-QNT', 'korean_name': '퀀트', 'english_name': 'Quant' },
# { 'market': 'BTC-CTXC', 'korean_name': '코르텍스', 'english_name': 'Cortex' },
# { 'market': 'BTC-SPND', 'korean_name': '스펜드코인', 'english_name': 'Spendcoin' },
# { 'market': 'BTC-META', 'korean_name': '메타디움', 'english_name': 'Metadium' },
# { 'market': 'KRW-MOC', 'korean_name': '모스코인', 'english_name': 'Moss Coin' },
# { 'market': 'BTC-ANKR', 'korean_name': '앵커', 'english_name': 'Ankr' },
# {
#   'market': 'BTC-CRO',
#   'korean_name': '크립토닷컴체인',
#   'english_name': 'Crypto.com Chain'
# },
# { 'market': 'KRW-ENJ', 'korean_name': '엔진코인', 'english_name': 'Enjin' },
# {
#   'market': 'KRW-TFUEL',
#   'korean_name': '쎄타퓨엘',
#   'english_name': 'Theta Fuel'
# },
# { 'market': 'BTC-FSN', 'korean_name': '퓨전', 'english_name': 'Fusion' },
# {
#   'market': 'KRW-MANA',
#   'korean_name': '디센트럴랜드',
#   'english_name': 'Decentraland'
# },
# { 'market': 'KRW-ANKR', 'korean_name': '앵커', 'english_name': 'Ankr' },
# { 'market': 'BTC-ORBS', 'korean_name': '오브스', 'english_name': 'Orbs' },
# { 'market': 'KRW-NPXS', 'korean_name': '펀디엑스', 'english_name': 'Pundi X' },
# { 'market': 'BTC-AERGO', 'korean_name': '아르고', 'english_name': 'Aergo' },
# { 'market': 'BTC-PI', 'korean_name': '피체인', 'english_name': 'PCHAIN' },
# { 'market': 'KRW-AERGO', 'korean_name': '아르고', 'english_name': 'Aergo' },
# { 'market': 'KRW-ATOM', 'korean_name': '코스모스', 'english_name': 'Cosmos' },
# {
#   'market': 'KRW-TT',
#   'korean_name': '썬더토큰',
#   'english_name': 'Thunder Token'
# },
# {
#   'market': 'KRW-CRE',
#   'korean_name': '캐리프로토콜',
#   'english_name': 'Carry Protocol'
# },
# {
#   'market': 'KRW-SOLVE',
#   'korean_name': '솔브케어',
#   'english_name': 'Solve.Care'
# },
# { 'market': 'BTC-ATOM', 'korean_name': '코스모스', 'english_name': 'Cosmos' },
# {
#   'market': 'BTC-STPT',
#   'korean_name': '에스티피',
#   'english_name': 'Standard Tokenization Protocol'
# },
# { 'market': 'KRW-MBL', 'korean_name': '무비블록', 'english_name': 'MovieBloc' },
# { 'market': 'BTC-LAMB', 'korean_name': '람다', 'english_name': 'Lambda' },
# { 'market': 'BTC-EOS', 'korean_name': '이오스', 'english_name': 'EOS' },
# { 'market': 'BTC-LUNA', 'korean_name': '루나', 'english_name': 'Luna' },
# { 'market': 'BTC-DAI', 'korean_name': '다이', 'english_name': 'Dai' },
# { 'market': 'BTC-MKR', 'korean_name': '메이커', 'english_name': 'Maker' },
# { 'market': 'BTC-BORA', 'korean_name': '보라', 'english_name': 'BORA' },
# { 'market': 'KRW-TSHP', 'korean_name': '트웰브쉽스', 'english_name': '12SHIPS' },
# { 'market': 'BTC-TSHP', 'korean_name': '트웰브쉽스', 'english_name': '12SHIPS' },
# { 'market': 'KRW-WAXP', 'korean_name': '왁스', 'english_name': 'WAX' },
# { 'market': 'BTC-WAXP', 'korean_name': '왁스', 'english_name': 'WAX' },
# {
#   'market': 'KRW-HBAR',
#   'korean_name': '헤데라해시그래프',
#   'english_name': 'Hedera Hashgraph'
# },
# { 'market': 'KRW-MED', 'korean_name': '메디블록', 'english_name': 'MediBloc' },
# { 'market': 'BTC-MED', 'korean_name': '메디블록', 'english_name': 'MediBloc' },
# { 'market': 'BTC-MLK', 'korean_name': '밀크', 'english_name': 'MiL.k' },
# { 'market': 'KRW-MLK', 'korean_name': '밀크', 'english_name': 'MiL.k' },
# { 'market': 'BTC-PXL', 'korean_name': '픽셀', 'english_name': 'PIXEL' },
# {
#   'market': 'KRW-STPT',
#   'korean_name': '에스티피',
#   'english_name': 'Standard Tokenization Protocol'
# },
# { 'market': 'BTC-VET', 'korean_name': '비체인', 'english_name': 'VeChain' },
# { 'market': 'KRW-ORBS', 'korean_name': '오브스', 'english_name': 'Orbs' },
# { 'market': 'BTC-CHZ', 'korean_name': '칠리즈', 'english_name': 'Chiliz' },
# { 'market': 'KRW-VET', 'korean_name': '비체인', 'english_name': 'VeChain' },
# { 'market': 'BTC-FX', 'korean_name': '펑션엑스', 'english_name': 'Function X' },
# {
#   'market': 'BTC-OGN',
#   'korean_name': '오리진프로토콜',
#   'english_name': 'Origin Protocol'
# },
# { 'market': 'KRW-CHZ', 'korean_name': '칠리즈', 'english_name': 'Chiliz' },
# { 'market': 'KRW-PXL', 'korean_name': '픽셀', 'english_name': 'PIXEL' },
# {
#   'market': 'BTC-ITAM',
#   'korean_name': '아이텀게임즈',
#   'english_name': 'Itam Games'
# },
# { 'market': 'BTC-XTZ', 'korean_name': '테조스', 'english_name': 'Tezos' },
# { 'market': 'BTC-HIVE', 'korean_name': '하이브', 'english_name': 'Hive' },
# {
#   'market': 'BTC-HBD',
#   'korean_name': '하이브달러',
#   'english_name': 'Hive Dollar'
# },
# { 'market': 'BTC-OBSR', 'korean_name': '옵저버', 'english_name': 'Observer' },
# { 'market': 'BTC-DKA', 'korean_name': '디카르고', 'english_name': 'dKargo' },
# { 'market': 'KRW-STMX', 'korean_name': '스톰엑스', 'english_name': 'StormX' },
# { 'market': 'BTC-STMX', 'korean_name': '스톰엑스', 'english_name': 'StormX' },
# { 'market': 'BTC-AHT', 'korean_name': '아하토큰', 'english_name': 'AhaToken' },
# { 'market': 'BTC-PCI', 'korean_name': '페이코인', 'english_name': 'PayCoin' },
# { 'market': 'BTC-RINGX', 'korean_name': '링엑스', 'english_name': 'RINGX' },
# { 'market': 'KRW-DKA', 'korean_name': '디카르고', 'english_name': 'dKargo' },
# { 'market': 'BTC-LINK', 'korean_name': '체인링크', 'english_name': 'Chainlink' },
# { 'market': 'KRW-HIVE', 'korean_name': '하이브', 'english_name': 'Hive' },
# { 'market': 'KRW-KAVA', 'korean_name': '카바', 'english_name': 'Kava' },
# { 'market': 'BTC-KAVA', 'korean_name': '카바', 'english_name': 'Kava' },
# { 'market': 'KRW-AHT', 'korean_name': '아하토큰', 'english_name': 'AhaToken' },
# { 'market': 'KRW-SPND', 'korean_name': '스펜드코인', 'english_name': 'Spendcoin' },
# { 'market': 'KRW-LINK', 'korean_name': '체인링크', 'english_name': 'Chainlink' },
# { 'market': 'KRW-XTZ', 'korean_name': '테조스', 'english_name': 'Tezos' },
# { 'market': 'KRW-BORA', 'korean_name': '보라', 'english_name': 'BORA' },
# { 'market': 'BTC-JST', 'korean_name': '저스트', 'english_name': 'JUST' },
# { 'market': 'BTC-CHR', 'korean_name': '크로미아', 'english_name': 'Chromia' },
# { 'market': 'BTC-DAD', 'korean_name': '다드', 'english_name': 'DAD' },
# { 'market': 'BTC-TON', 'korean_name': '톤', 'english_name': 'TON' },
# { 'market': 'KRW-JST', 'korean_name': '저스트', 'english_name': 'JUST' },
# { 'market': 'BTC-CTSI', 'korean_name': '카르테시', 'english_name': 'Cartesi' },
# { 'market': 'BTC-DOT', 'korean_name': '폴카닷', 'english_name': 'Polkadot' },
# {
#   'market': 'KRW-CRO',
#   'korean_name': '크립토닷컴체인',
#   'english_name': 'Crypto.com Chain'
# },
# { 'market': 'BTC-COMP', 'korean_name': '컴파운드', 'english_name': 'Compound' },
# { 'market': 'BTC-SXP', 'korean_name': '스와이프', 'english_name': 'Swipe' },
# { 'market': 'BTC-HUNT', 'korean_name': '헌트', 'english_name': 'HUNT' },
# { 'market': 'KRW-TON', 'korean_name': '톤', 'english_name': 'TON' },
# { 'market': 'BTC-ONIT', 'korean_name': '온버프', 'english_name': 'ONBUFF' },
# { 'market': 'BTC-CRV', 'korean_name': '커브', 'english_name': 'Curve' },
# { 'market': 'BTC-ALGO', 'korean_name': '알고랜드', 'english_name': 'Algorand' },
# {
#   'market': 'BTC-RSR',
#   'korean_name': '리저브라이트',
#   'english_name': 'Reserve Rights'
# },
# { 'market': 'KRW-SXP', 'korean_name': '스와이프', 'english_name': 'Swipe' },
# { 'market': 'BTC-OXT', 'korean_name': '오키드', 'english_name': 'Orchid' },
# { 'market': 'BTC-PLA', 'korean_name': '플레이댑', 'english_name': 'PlayDapp' },
# { 'market': 'KRW-LAMB', 'korean_name': '람다', 'english_name': 'Lambda' },
# { 'market': 'KRW-HUNT', 'korean_name': '헌트', 'english_name': 'HUNT' },
# { 'market': 'BTC-MARO', 'korean_name': '마로', 'english_name': 'Maro' },
# { 'market': 'KRW-MARO', 'korean_name': '마로', 'english_name': 'Maro' },
# {
#   'market': 'BTC-SAND',
#   'korean_name': '샌드박스',
#   'english_name': 'The Sandbox'
# },
# { 'market': 'BTC-SUN', 'korean_name': '썬', 'english_name': 'SUN' },
# { 'market': 'KRW-PLA', 'korean_name': '플레이댑', 'english_name': 'PlayDapp' },
# { 'market': 'KRW-DOT', 'korean_name': '폴카닷', 'english_name': 'Polkadot' },
# { 'market': 'BTC-SRM', 'korean_name': '세럼', 'english_name': 'Serum' },
# { 'market': 'BTC-QTCON', 'korean_name': '퀴즈톡', 'english_name': 'Quiztok' },
# { 'market': 'BTC-MVL', 'korean_name': '엠블', 'english_name': 'MVL' },
# { 'market': 'KRW-SRM', 'korean_name': '세럼', 'english_name': 'Serum' },
# { 'market': 'KRW-MVL', 'korean_name': '엠블', 'english_name': 'MVL' },
# { 'market': 'BTC-GXC', 'korean_name': '지엑스체인', 'english_name': 'GXChain' },
# { 'market': 'KRW-PCI', 'korean_name': '페이코인', 'english_name': 'PayCoin' },
# {
#   'market': 'BTC-AQT',
#   'korean_name': '알파쿼크',
#   'english_name': 'Alpha Quark Token'
# },
# {
#   'market': 'BTC-AXS',
#   'korean_name': '엑시인피니티',
#   'english_name': 'Axie Infinity'
# },
# { 'market': 'BTC-STRAX', 'korean_name': '스트라티스', 'english_name': 'Stratis' },
# { 'market': 'KRW-STRAX', 'korean_name': '스트라티스', 'english_name': 'Stratis' },
# {
#   'market': 'KRW-AQT',
#   'korean_name': '알파쿼크',
#   'english_name': 'Alpha Quark Token'
# },
# {
#   'market': 'BTC-BCHA',
#   'korean_name': '비트코인캐시에이비씨',
#   'english_name': 'Bitcoin Cash ABC'
# },
# {
#   'market': 'KRW-BCHA',
#   'korean_name': '비트코인캐시에이비씨',
#   'english_name': 'Bitcoin Cash ABC'
# },
# { 'market': 'BTC-GLM', 'korean_name': '골렘', 'english_name': 'Golem' },
# { 'market': 'KRW-GLM', 'korean_name': '골렘', 'english_name': 'Golem' },
# { 'market': 'KRW-QTCON', 'korean_name': '퀴즈톡', 'english_name': 'Quiztok' },
# {
#   'market': 'BTC-FCT2',
#   'korean_name': '피르마체인',
#   'english_name': 'FirmaChain'
# },
# { 'market': 'BTC-SSX', 'korean_name': '썸씽', 'english_name': 'SOMESING' },
# { 'market': 'KRW-SSX', 'korean_name': '썸씽', 'english_name': 'SOMESING' },
# { 'market': 'KRW-META', 'korean_name': '메타디움', 'english_name': 'Metadium' },
# { 'market': 'KRW-OBSR', 'korean_name': '옵저버', 'english_name': 'Observer' },
# {
#   'market': 'KRW-FCT2',
#   'korean_name': '피르마체인',
#   'english_name': 'FirmaChain'
# },
# { 'market': 'BTC-FIL', 'korean_name': '파일코인', 'english_name': 'Filecoin' },
# {
#   'market': 'KRW-LBC',
#   'korean_name': '엘비알와이크레딧',
#   'english_name': 'LBRY Credits'
# },
# { 'market': 'BTC-UNI', 'korean_name': '유니스왑', 'english_name': 'Uniswap' },
# { 'market': 'BTC-BASIC', 'korean_name': '베이직', 'english_name': 'Basic' },
# {
#   'market': 'BTC-INJ',
#   'korean_name': '인젝티브프로토콜',
#   'english_name': 'Injective Protocol'
# },
# {
#   'market': 'BTC-PROM',
#   'korean_name': '프로메테우스',
#   'english_name': 'Prometeus'
# },
# { 'market': 'BTC-VAL', 'korean_name': '밸리디티', 'english_name': 'Validity' },
# {
#   'market': 'BTC-PSG',
#   'korean_name': '파리생제르맹',
#   'english_name': 'Paris Saint-Germain Fan Token'
# },
# {
#   'market': 'BTC-JUV',
#   'korean_name': '유벤투스',
#   'english_name': 'Juventus Fan Token'
# },
# { 'market': 'BTC-CBK', 'korean_name': '코박토큰', 'english_name': 'Cobak Token' },
# { 'market': 'BTC-FOR', 'korean_name': '포튜브', 'english_name': 'ForTube' },
# { 'market': 'KRW-CBK', 'korean_name': '코박토큰', 'english_name': 'Cobak Token' },
# { 'market': 'BTC-BFC', 'korean_name': '바이프로스트', 'english_name': 'Bifrost' },
# { 'market': 'BTC-LINA', 'korean_name': '리니어파이낸스', 'english_name': 'Linear' },
# {
#   'market': 'BTC-HUM',
#   'korean_name': '휴먼스케이프',
#   'english_name': 'Humanscape'
# },
# { 'market': 'BTC-PICA', 'korean_name': '피카', 'english_name': 'Pica' },
# { 'market': 'BTC-CELO', 'korean_name': '셀로', 'english_name': 'Celo' },
# {
#   'market': 'KRW-SAND',
#   'korean_name': '샌드박스',
#   'english_name': 'The Sandbox'
# },
# {
#   'market': 'KRW-HUM',
#   'korean_name': '휴먼스케이프',
#   'english_name': 'Humanscape'
# },
# { 'market': 'BTC-IQ', 'korean_name': '에브리피디아', 'english_name': 'Everipedia' },
# { 'market': 'BTC-STX', 'korean_name': '스택스', 'english_name': 'Stacks' },
# { 'market': 'KRW-DOGE', 'korean_name': '도지코인', 'english_name': 'Dogecoin' },
# {
#   'market': 'BTC-NEAR',
#   'korean_name': '니어프로토콜',
#   'english_name': 'NEAR Protocol'
# },
# { 'market': 'BTC-AUCTION', 'korean_name': '바운스토큰', 'english_name': 'Bounce' },
# {
#   'market': 'BTC-DAWN',
#   'korean_name': '던프로토콜',
#   'english_name': 'Dawn Protocol'
# }
# ]

coinList = {
'KRW-BTC' : '비트코인',
'KRW-ETH' : '이더리움',
'BTC-ETH' : '이더리움',
'BTC-LTC' : '라이트코인',
'BTC-XRP' : '리플',
'BTC-ETC' : '이더리움클래식',
'BTC-OMG' : '오미세고',
'BTC-CVC' : '시빅',
'BTC-DGB' : '디지바이트',
'BTC-PAY' : '텐엑스페이토큰',
'BTC-SC' : '시아코인',
'BTC-SNT' : '스테이터스네트워크토큰',
'BTC-WAVES' : '웨이브',
'BTC-NMR' : '뉴메레르',
'BTC-XEM' : '넴',
'BTC-LBC' : '엘비알와이크레딧',
'BTC-QTUM' : '퀀텀',
'BTC-NXT' : '엔엑스티',
'BTC-BAT' : '베이직어텐션토큰',
'BTC-LSK' : '리스크',
'BTC-RDD' : '레드코인',
'BTC-STEEM' : '스팀',
'BTC-DOGE' : '도지코인',
'BTC-BNT' : '뱅코르',
'BTC-XLM' : '스텔라루멘',
'BTC-ARDR' : '아더',
'BTC-KMD' : '코모도',
'BTC-ARK' : '아크',
'BTC-ADX' : '애드엑스',
'BTC-SYS' : '시스코인',
'BTC-ANT' : '아라곤',
'BTC-STORJ' : '스토리지',
'BTC-GRS' : '그로스톨코인',
'BTC-REP' : '어거',
'BTC-RLC' : '아이젝',
'BTC-EMC2' : '아인스타이늄',
'USDT-BTC' : '비트코인',
'USDT-ETH' : '이더리움',
'USDT-LTC' : '라이트코인',
'USDT-XRP' : '리플',
'USDT-ETC' : '이더리움클래식',
'KRW-NEO' : '네오',
'KRW-MTL' : '메탈',
'KRW-LTC' : '라이트코인',
'KRW-XRP' : '리플',
'KRW-ETC' : '이더리움클래식',
'KRW-OMG' : '오미세고',
'KRW-SNT' : '스테이터스네트워크토큰',
'KRW-WAVES' : '웨이브',
'KRW-XEM' : '넴',
'KRW-QTUM' : '퀀텀',
'KRW-LSK' : '리스크',
'KRW-STEEM' : '스팀',
'KRW-XLM' : '스텔라루멘',
'KRW-ARDR' : '아더',
'KRW-KMD' : '코모도',
'KRW-ARK' : '아크',
'KRW-STORJ' : '스토리지',
'KRW-GRS' : '그로스톨코인',
'KRW-REP' : '어거',
'KRW-EMC2' : '아인스타이늄',
'KRW-ADA' : '에이다',
'BTC-ADA' : '에이다',
'BTC-MANA' : '디센트럴랜드',
'USDT-OMG' : '오미세고',
'KRW-SBD' : '스팀달러',
'BTC-SBD' : '스팀달러',
'BTC-RCN' : '리피오크레딧네트워크',
'BTC-VIB' : '바이버레이트',
'KRW-POWR' : '파워렛저',
'BTC-POWR' : '파워렛저',
'KRW-BTG' : '비트코인골드',
'USDT-ADA' : '에이다',
'BTC-DNT' : '디스트릭트0x',
'BTC-IGNIS' : '이그니스',
'BTC-SRN' : '시린토큰',
'BTC-ZRX' : '제로엑스',
'BTC-TRX' : '트론',
'BTC-TUSD' : '트루USD',
'BTC-LRC' : '루프링',
'KRW-ICX' : '아이콘',
'KRW-EOS' : '이오스',
'BTC-DMT' : '디마켓',
'USDT-TUSD' : '트루USD',
'KRW-TRX' : '트론',
'BTC-POLY' : '폴리매쓰',
'BTC-PRO' : '프로피',
'USDT-SC' : '시아코인',
'USDT-TRX' : '트론',
'KRW-SC' : '시아코인',
'KRW-IGNIS' : '이그니스',
'KRW-ONT' : '온톨로지',
'KRW-ZIL' : '질리카',
'KRW-POLY' : '폴리매쓰',
'KRW-ZRX' : '제로엑스',
'KRW-SRN' : '시린토큰',
'KRW-LOOM' : '룸네트워크',
'BTC-BCH' : '비트코인캐시',
'USDT-BCH' : '비트코인캐시',
'KRW-BCH' : '비트코인캐시',
'BTC-MFT' : '메인프레임',
'BTC-LOOM' : '룸네트워크',
'KRW-ADX' : '애드엑스',
'KRW-BAT' : '베이직어텐션토큰',
'KRW-IOST' : '아이오에스티',
'BTC-RFR' : '리퍼리움',
'KRW-DMT' : '디마켓',
'KRW-RFR' : '리퍼리움',
'USDT-DGB' : '디지바이트',
'KRW-CVC' : '시빅',
'KRW-IQ' : '에브리피디아',
'KRW-IOTA' : '아이오타',
'BTC-RVN' : '레이븐코인',
'BTC-BFT' : '비에프토큰',
'BTC-GO' : '고체인',
'BTC-UPP' : '센티넬프로토콜',
'BTC-ENJ' : '엔진코인',
'KRW-MFT' : '메인프레임',
'BTC-DTA' : '데이터',
'BTC-EDR' : '엔도르',
'KRW-ONG' : '온톨로지가스',
'KRW-GAS' : '가스',
'BTC-MTL' : '메탈',
'KRW-UPP' : '센티넬프로토콜',
'KRW-ELF' : '엘프',
'BTC-PMA' : '퓨마페이',
'USDT-DOGE' : '도지코인',
'USDT-ZRX' : '제로엑스',
'USDT-RVN' : '레이븐코인',
'USDT-BAT' : '베이직어텐션토큰',
'KRW-KNC' : '카이버네트워크',
'BTC-PAX' : '팩소스스탠다드',
'BTC-MOC' : '모스코인',
'BTC-NPXS' : '펀디엑스',
'BTC-ZIL' : '질리카',
'KRW-BSV' : '비트코인에스브이',
'BTC-BSV' : '비트코인에스브이',
'BTC-IOST' : '아이오에스티',
'KRW-THETA' : '쎄타토큰',
'BTC-NCASH' : '뉴클리어스비전',
'KRW-EDR' : '엔도르',
'BTC-DENT' : '덴트',
'KRW-QKC' : '쿼크체인',
'BTC-BTM' : '바이텀',
'BTC-ELF' : '엘프',
'KRW-BTT' : '비트토렌트',
'BTC-BTT' : '비트토렌트',
'BTC-VITE' : '비트토큰',
'BTC-IOTX' : '아이오텍스',
'BTC-SOLVE' : '솔브케어',
'BTC-NKN' : '엔케이엔',
'BTC-QNT' : '퀀트',
'BTC-CTXC' : '코르텍스',
'BTC-SPND' : '스펜드코인',
'BTC-META' : '메타디움',
'KRW-MOC' : '모스코인',
'BTC-ANKR' : '앵커',
'BTC-CRO' : '크립토닷컴체인',
'KRW-ENJ' : '엔진코인',
'KRW-TFUEL' : '쎄타퓨엘',
'BTC-FSN' : '퓨전',
'KRW-MANA' : '디센트럴랜드',
'KRW-ANKR' : '앵커',
'BTC-ORBS' : '오브스',
'KRW-NPXS' : '펀디엑스',
'BTC-AERGO' : '아르고',
'BTC-PI' : '피체인',
'KRW-AERGO' : '아르고',
'KRW-ATOM' : '코스모스',
'KRW-TT' : '썬더토큰',
'KRW-CRE' : '캐리프로토콜',
'KRW-SOLVE' : '솔브케어',
'BTC-ATOM' : '코스모스',
'BTC-STPT' : '에스티피',
'KRW-MBL' : '무비블록',
'BTC-LAMB' : '람다',
'BTC-EOS' : '이오스',
'BTC-LUNA' : '루나',
'BTC-DAI' : '다이',
'BTC-MKR' : '메이커',
'BTC-BORA' : '보라',
'KRW-TSHP' : '트웰브쉽스',
'BTC-TSHP' : '트웰브쉽스',
'KRW-WAXP' : '왁스',
'BTC-WAXP' : '왁스',
'KRW-HBAR' : '헤데라해시그래프',
'KRW-MED' : '메디블록',
'BTC-MED' : '메디블록',
'BTC-MLK' : '밀크',
'KRW-MLK' : '밀크',
'BTC-PXL' : '픽셀',
'KRW-STPT' : '에스티피',
'BTC-VET' : '비체인',
'KRW-ORBS' : '오브스',
'BTC-CHZ' : '칠리즈',
'KRW-VET' : '비체인',
'BTC-FX' : '펑션엑스',
'BTC-OGN' : '오리진프로토콜',
'KRW-CHZ' : '칠리즈',
'KRW-PXL' : '픽셀',
'BTC-ITAM' : '아이텀게임즈',
'BTC-XTZ' : '테조스',
'BTC-HIVE' : '하이브',
'BTC-HBD' : '하이브달러',
'BTC-OBSR' : '옵저버',
'BTC-DKA' : '디카르고',
'KRW-STMX' : '스톰엑스',
'BTC-STMX' : '스톰엑스',
'BTC-AHT' : '아하토큰',
'BTC-PCI' : '페이코인',
'BTC-RINGX' : '링엑스',
'KRW-DKA' : '디카르고',
'BTC-LINK' : '체인링크',
'KRW-HIVE' : '하이브',
'KRW-KAVA' : '카바',
'BTC-KAVA' : '카바',
'KRW-AHT' : '아하토큰',
'KRW-SPND' : '스펜드코인',
'KRW-LINK' : '체인링크',
'KRW-XTZ' : '테조스',
'KRW-BORA' : '보라',
'BTC-JST' : '저스트',
'BTC-CHR' : '크로미아',
'BTC-DAD' : '다드',
'BTC-TON' : '톤',
'KRW-JST' : '저스트',
'BTC-CTSI' : '카르테시',
'BTC-DOT' : '폴카닷',
'KRW-CRO' : '크립토닷컴체인',
'BTC-COMP' : '컴파운드',
'BTC-SXP' : '스와이프',
'BTC-HUNT' : '헌트',
'KRW-TON' : '톤',
'BTC-ONIT' : '온버프',
'BTC-CRV' : '커브',
'BTC-ALGO' : '알고랜드',
'BTC-RSR' : '리저브라이트',
'KRW-SXP' : '스와이프',
'BTC-OXT' : '오키드',
'BTC-PLA' : '플레이댑',
'KRW-LAMB' : '람다',
'KRW-HUNT' : '헌트',
'BTC-MARO' : '마로',
'KRW-MARO' : '마로',
'BTC-SAND' : '샌드박스',
'BTC-SUN' : '썬',
'KRW-PLA' : '플레이댑',
'KRW-DOT' : '폴카닷',
'BTC-SRM' : '세럼',
'BTC-QTCON' : '퀴즈톡',
'BTC-MVL' : '엠블',
'KRW-SRM' : '세럼',
'KRW-MVL' : '엠블',
'BTC-GXC' : '지엑스체인',
'KRW-PCI' : '페이코인',
'BTC-AQT' : '알파쿼크',
'BTC-AXS' : '엑시인피니티',
'BTC-STRAX' : '스트라티스',
'KRW-STRAX' : '스트라티스',
'KRW-AQT' : '알파쿼크',
'BTC-BCHA' : '비트코인캐시에이비씨',
'KRW-BCHA' : '비트코인캐시에이비씨',
'BTC-GLM' : '골렘',
'KRW-GLM' : '골렘',
'KRW-QTCON' : '퀴즈톡',
'BTC-FCT2' : '피르마체인',
'BTC-SSX' : '썸씽',
'KRW-SSX' : '썸씽',
'KRW-META' : '메타디움',
'KRW-OBSR' : '옵저버',
'KRW-FCT2' : '피르마체인',
'BTC-FIL' : '파일코인',
'KRW-LBC' : '엘비알와이크레딧',
'BTC-UNI' : '유니스왑',
'BTC-BASIC' : '베이직',
'BTC-INJ' : '인젝티브프로토콜',
'BTC-PROM' : '프로메테우스',
'BTC-VAL' : '밸리디티',
'BTC-PSG' : '파리생제르맹',
'BTC-JUV' : '유벤투스',
'BTC-CBK' : '코박토큰',
'BTC-FOR' : '포튜브',
'KRW-CBK' : '코박토큰',
'BTC-BFC' : '바이프로스트',
'BTC-LINA' : '리니어파이낸스',
'BTC-HUM' : '휴먼스케이프',
'BTC-PICA' : '피카',
'BTC-CELO' : '셀로',
'KRW-SAND' : '샌드박스',
'KRW-HUM' : '휴먼스케이프',
'BTC-IQ' : '에브리피디아',
'BTC-STX' : '스택스',
'KRW-DOGE' : '도지코인',
'BTC-NEAR' : '니어프로토콜',
'BTC-AUCTION' : '바운스토큰',
'BTC-DAWN' : '던프로토콜'
}
#
#
# for one in coinList:
#   print(f"'{one['market']}' : '{one['korean_name']}',")